# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{oink}
  s.version = "0.9.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Noah Davis"]
  s.date = %q{2011-04-05}
  s.default_executable = %q{oink}
  s.description = %q{Log parser to identify actions which significantly increase VM heap size}
  s.email = %q{noahd1@yahoo.com}
  s.executables = ["oink"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "bin/oink",
    "lib/oink.rb",
    "lib/oink/cli.rb",
    "lib/oink/instrumentation.rb",
    "lib/oink/instrumentation/active_record.rb",
    "lib/oink/instrumentation/memory_snapshot.rb",
    "lib/oink/middleware.rb",
    "lib/oink/rails.rb",
    "lib/oink/rails/instance_type_counter.rb",
    "lib/oink/rails/memory_usage_logger.rb",
    "lib/oink/reports/active_record_instantiation_oinked_request.rb",
    "lib/oink/reports/active_record_instantiation_report.rb",
    "lib/oink/reports/base.rb",
    "lib/oink/reports/memory_oinked_request.rb",
    "lib/oink/reports/memory_usage_report.rb",
    "lib/oink/reports/priority_queue.rb",
    "lib/oink/reports/request.rb",
    "lib/oink/utils/hash_utils.rb"
  ]
  s.homepage = %q{http://github.com/noahd1/oink}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Log parser to identify actions which significantly increase VM heap size}
  s.test_files = [
    "spec/fakes/fake_application_controller.rb",
    "spec/fakes/psuedo_output.rb",
    "spec/helpers/database.rb",
    "spec/oink/instrumentation/instance_type_counter_spec.rb",
    "spec/oink/instrumentation/memory_snapshot_spec.rb",
    "spec/oink/middleware_configuration_spec.rb",
    "spec/oink/middleware_spec.rb",
    "spec/oink/rails/instance_type_counter_spec.rb",
    "spec/oink/rails/memory_usage_logger_spec.rb",
    "spec/oink/reports/active_record_instantiation_report_spec.rb",
    "spec/oink/reports/memory_usage_report_spec.rb",
    "spec/oink/reports/oinked_request_spec.rb",
    "spec/oink/reports/priority_queue_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hodel_3000_compliant_logger>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
    else
      s.add_dependency(%q<hodel_3000_compliant_logger>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
    end
  else
    s.add_dependency(%q<hodel_3000_compliant_logger>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
  end
end

